print("I like to explore haunted places")
print("I ussually dont interact more with ppl")
print("I love to read psychology, money and lifestyle books")
print("I imagine a lot write novels tht am planning to publish later")
print("I like to play chess and 8 ball pool")
print("I was a district level swimmer and district level skater when i was in 5th grd")
print("My native is pudukkottai but it had less educational fesilities so we moved to hosur ")
print("I like to travell and explore new stuffs")
print("I get bored ussually when am home and doin nothin (0.0)")
print("Am bad at explaining myself and emotions")
print("I work out everyday tdy was my leg ahh tiering")
print("My deadlift pr yesterday was my personal best and its 120 kg")
print("i go to gym occationally with my best frnds (not daily like 2 or 3 tyms a week)")
print("Last month my bench press pr was 60 kg and ig now i might push my limits")
print("i was a topper when i studied my 10th grade.")
print("I neglected working hard on 11th and 12th and lost my mark")
print("I scored 91% in 10th")
print("I scored 80 in 12th")
print("When others sat day and ni8 studying for their board exam me and my frnds were riding around")
print("now am on track agn  strted working for becomming an benchmark in my clg")
print("20 over!!")
